// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rburgxsgpjdunkxyyrkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJidXJneHNncGpkdW5reHl5cmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5Nzg0NjAsImV4cCI6MjA3ODU1NDQ2MH0.eN23GioqBdrRpjkkSeHkx9hFkr5_8zuzKKWeW3w6Mkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);